# Generated by Django 2.2.1 on 2019-05-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('articulo', models.CharField(max_length=5000)),
                ('votos', models.IntegerField(default=0)),
                ('idArticulo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idComentario', models.IntegerField(default=0)),
                ('cita', models.CharField(max_length=5000)),
                ('comentario', models.CharField(max_length=5000)),
                ('votos', models.IntegerField(default=0)),
            ],
        ),
    ]
