# Generated by Django 2.2.1 on 2019-05-11 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_auto_20190511_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='comentarios_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='articulos.Comentario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='idArticulo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tipo',
            field=models.IntegerField(default=1),
        ),
    ]
