# Generated by Django 2.2.1 on 2019-05-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_auto_20190511_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='comentarios_id',
        ),
        migrations.AddField(
            model_name='comentario',
            name='idComentarioPadre',
            field=models.IntegerField(default=0),
        ),
    ]
